export const symbolForIdentifier = "@enkore/js-runtime/globalRecords"
export const freezeObjectHelperMethodName = "__enkoreJSRuntimeFreezeObject"
export const freezeGlobalDataRecordMethodName = "__enkoreJSRuntimeFreezeGlobalDataRecord"
export const initMethodName = "__enkoreJSRuntimeInitialize"
export const debugLogMethodName = "__enkoreJSRuntimeDebugLog"
