export const oldSymbolForIdentifier = "@enkore/js-runtime/globalRecords"
export const symbolForInitializedGlobalRecords = "@enkore/js-runtime/initializedGlobalRecords"
export const freezeObjectHelperMethodName = "__enkoreJSRuntimeFreezeObject"
export const freezeGlobalDataRecordMethodName = "__enkoreJSRuntimeFreezeGlobalDataRecord"
export const initMethodName = "__enkoreJSRuntimeInitialize"
export const debugLogMethodName = "__enkoreJSRuntimeDebugLog"
export const nodeCommonJSRequire = "__enkoreJSRuntimeNodeCommonJSRequire"
